spring:
  application:
    name: news-assistant
  ai:
    ollama:
      chat:
        options:
          model: qwen2.5
        enabled: true
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/abc?characterEncoding=utf8&allowMultiQueries=true
    username: root

server:
  port: 8089

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    const-sampler:
      decision: true
    enabled: true

