spring:
  application:
    name: llm-interface
  ai:
    ollama:
      chat:
        options:
          model: qwen2.5
        enabled: true
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:~/test
#    hikari:
#      username: sa
  datasource:
#    url: jdbc:sqlite::resource:db/studio.db
#    url: jdbc:sqlite:D:\Project\studio.db
    url: jdbc:sqlite:db/studio.db
    driver-class-name: org.sqlite.JDBC


#  jpa:
#    database-platform: org.hibernate.community.dialect.SQLiteDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true

server:
  port: 9000

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 4317
    const-sampler:
      decision: true
    enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    map-underscore-to-camel-case: true